version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend/chat-app
    ports:
      - "80:80"
    environment:
      - REACT_APP_WEBSOCKET_URL=ws://backend:8000
    depends_on:
      - backend
